# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - run: npm install @zeit/next-bundle-analyzer
    - run: npm install @zeit/next-css
    - run: npm install antd
    - run: npm install atob
    - run: npm install babel-plugin-import
    - run: npm install babel-plugin-styled-components
    - run: npm install cross-env
    - run: npm install github-markdown-css
    - run: npm install ioredis
    - run: npm install koa-body
    - run: npm install koa-router
    - run: npm install koa-session
    - run: npm install lru-cache
    - run: npm install markdown-it
    - run: npm install moment
    - run: npm install react-redux
    - run: npm install redux
    - run: npm install redux-devtools-extension
    - run: npm install redux-thunk
    - run: npm install styled-components
    - run: npm ci
    - run: npm run build
    - run: npm run export
    
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: out # The folder the action should deploy.
